### ISSUE TITLE
methods unavailable with no_std

### ISSUE THREAD

**Issue by tormol** [tomprogrammer/rust-ascii#24]
`AsciiExt` and `Error` are not in core, but some of their methods might still be useful.  
We can add feature-gated inherent impls for those methods, but should we?

* `description()` for `ToAsciiCharError` and `AsAsciiStrError`
* `eq_ignore_case()` for `AsciiChar` and `AsciiStr`
* `to_ascii_{upper,lower}case()` for `AsciiChar`
* `make_ascii_{upper,lower}case()` for `AsciiStr`

**Comment by tomprogrammer** [comment]
Hello tormol,

the methods you mentioned are part of traits that only exist in `std`. Since these are unlikely to be added to `core` it seems reasonable to provide the methods as inherent implementations.

I have only a single question: Is the `description()` method useful in a `core`-only environment? I doubt that other error structs or enums implement that method originally from `std::error::Error`.

**Comment by tormol** [comment]
Hmm, I guess people would write their own error messages before release, but it might be used while prototyping.
Even if they're useless I think they should be there for completeness sake.

I don't understand your last sentence: do you mean nobody would add a description method if it wasn't required by `Error`?

**Comment by tomprogrammer** [comment]
Yes, I was not sure how people handle errors in a `core`-only environment. You understood my question correctly. I agree with you that the `description` method can be useful to avoid forcing users of this library to write their own error messages.

I think we should implement all methods you mentioned behind a feature-gate.

**Comment by tomprogrammer** [comment]
Fixed in #26
