### ISSUE TITLE
Switch to quickcheck 0.4?

### ISSUE THREAD

**Issue by sid0** [tomprogrammer/rust-ascii#37]
I noticed in https://github.com/tomprogrammer/rust-ascii/blob/master/Cargo.toml#L12 that we're specifying quickcheck 0.4.1, not a general "^0.4" or "^0.4.1". Would it make sense to specify that instead?

(Sorry, didn't realize that while looking at it earlier!)

**Comment by tomprogrammer** [comment]
According to the cargo documentation about [specifying dependencies](http://doc.crates.io/specifying-dependencies.html) a version string without an operator is equivalent to specifying it using the caret operator. The `cargo-add` tool that I used writes dependency information without the caret for that reason, I guess.

That means the version requirement "0.4.1" behaves like "^0.4.1" and we don't need to change it. I'm closing the issue because your issue is solved. If it isn't, don't hesitate to reopen it.

**Comment by sid0** [comment]
Ah, I completely missed that bit. Thanks!
