### ISSUE TITLE
Update quickcheck dependency to 0.8

### ISSUE THREAD

**Issue by silwol** [tomprogrammer/rust-ascii#61]
The `quickcheck` crate has been updated to 0.8 since the last release of `ascii` which depends on 0.6.
In Debian, we usually package the latest version of crates except if there is a compelling reason to package earlier versions in addition.
See also [Debian Bug #927314](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=927314).

**Comment by tormol** [comment]
It will likely be trivial to do, but [updating quickcheck has previously been considered a breaking change](https://github.com/tomprogrammer/rust-ascii/pull/49), in which case you would also need the reverse dependencies to update their ascii dependency.
quickcheck is only an optional dependency though; does any of the reverse dependencies packaged by debian actually need it? (I couldn't find a way to get the reverse dependencies of a package on packages.debian.org)

**Comment by silwol** [comment]
Yes, there is currently no direct way to detect the reverse dependencies due to crate packages only being build dependencies in Debian. A method to find these dependencies is described in the `TODO.rst` file in [the debcargo-conf repository](https://salsa.debian.org/rust-team/debcargo-conf).
The packaged reverse dependencies currently are `combine` and `encode-unicode`, which in turn are not yet depended on, and as far as I can say, none of these uses the quickcheck feature.
This means `ascii` is not used in any binary package yet, but it is present in a dependency tree of a binary crate we intend to package on the long term.
It would be easy for us to patch out the quickcheck feature, but we usually try to stay close to upstream and avoid patching if not necessary. Instead we try to get crate maintainers to update their dependencies, because we might package a crate one day which requires the quickcheck feature, and then it would cause more troubles than if we had tried to get the fixes into upstream early.
For Debian 10 (buster) no binary crate will use `ascii`, because we are in freeze already and it will be released soon(ish). So we have some time left to work towards Debian 11 (bullseye) to get the depending crates packaged and updated.

**Comment by silwol** [comment]
Any updates on this? Now that buster is released, I would like to continue packaging. If you consider releasing a new (semver incompatible) `ascii` version, I would wait for it to be released, otherwise I would rather patch our package to not contain the `quickcheck` feature.

**Comment by tormol** [comment]
I tried to update quickcheck a while ago, and it turned out to be more complicated than I thought it would, because quickcheck 0.8 doesn't depend on rand, but only rand-core.

Instead I want to remove quickcheck:
I'd like the next semver-incompatible release to be 1.0, and quickcheck being <1.0 makes that difficult. While I don't like how Debian considers a problem with an unused opt-in feature release-critical to the base package (especially one AFAIK only useful for testing like quickcheck), I'd rather help Debian than facebook (who requested the feature originally). 

If @tomprogrammer is OK with this, I can remove quickcheck (and finish up my breaking changes at https://github.com/tormol/rust-ascii/commits/breaking) this weekend.

**Comment by tomprogrammer** [comment]
Hi @tormol,

I also tried updating it and came to the same conclusion. The problem is, that the features `quickcheck` is named like the optional dependency, so we can't make the compilation of `rand` dependent on the feature `quickcheck`.

A possible solution would be renaming the feature so we can properly include the `rand` dependency, but thats my least favourite option.

I also thought about removing the quickcheck feature, instead users should use a newtype-wrapper that implements the required traits.  Maybe @sunshowers can provide feedback on that, as original requester of this feature. Another advantage would be, that fewer major releases have to be cut for `ascii`.

While the `quickcheck` feature is mostly used in tests of other crates disabling the feature in the official Debian package could be a problem. Building the deb package could include running these tests, that require the feature. Therefore I think the Debian package indeed should enable all features.

**Comment by silwol** [comment]
@tormol With my debian maintainer hat on, I would really appreciate your suggested solution of removing the quickcheck dependency. Would facilitate maintenance significantly.
@tomprogrammer We are indeed right now starting to use autopkgtests which run tests for all features during build :-)

**Comment by tormol** [comment]
quickcheck feature has been removed with version 1.0.0.

Sorry it took me so long to finish up #63.
