### ISSUE TITLE
`serde_test` should be dev-dependency

### ISSUE THREAD

**Issue by Mingun** [tomprogrammer/rust-ascii#99]
If I'm not missing something, it is required only for tests, so it should be in the `[dev-dependencies]` section

**Comment by tormol** [comment]
serde [is an optional dependency](https://github.com/tomprogrammer/rust-ascii/blob/master/Cargo.toml#L12), so how does one add a feature-specific dev-dependency?

I tried
```toml
[target.'cfg(feature="serde")'.dev-dependencies]
serde_test = "1.0"
```
but cargo warns that it doesn't work as expected, and `extern crate serde_test;` fails. (With and without `resolver = "2"`).

Is it the norm to require all features to build tests?

(I've also asked about this [in an r/rust questions thread](https://old.reddit.com/r/rust/comments/1414cqf/hey_rustaceans_got_a_question_ask_here_232023/jn102ov/), but since this [isn't the only project with optional serde support you've opened an issue for](https://github.com/contain-rs/linear-map/issues/40), I guess you know.)

**Comment by tormol** [comment]
Based on [your comment on circular-queue](https://github.com/YaLTeR/circular-queue/pull/7/files#diff-2e9d962a08321605940b5a657135052fbcef87b5e360662bb527c96d9a615542) I tried just doing
```toml
[dev-dependencies]
serde_test = "1.0"
```
but when I run `cargo build --no-default-features --tests` I get
```
   Compiling serde v1.0.163
   Compiling serde_test v1.0.163
   Compiling ascii v1.1.0 (/home/tbm/p/rust/libs/ascii)
    Finished dev [unoptimized + debuginfo] target(s) in 1.93s
```
even though serde was not enabled.
so what you said about the `serde_test` dependency not being compiled appears not to be the case.

**Comment by Mingun** [comment]
Hm, I tried to provide compilation of quick-xml which have only one required dependency, but `cargo test --no-default-features` builds all libraries listed in `[dev-dependencies]` section, even unused for the selected test options (for example, `tokio-test` which needed only when enabling `async-tokio` feature). So it seems that my assumption is wrong and I observed some other effect that reduced number of used libraries.
